require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "0"

# Required b/c podspec Swift dependencies on Folly, etc.
use_modular_headers!

# Required b/c duplicate module headers
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

target 'BlobCourierExample' do
  config = use_native_modules!

  pod 'React-RCTFabric', :path => '../node_modules/react-native/React', :modular_headers => false

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :flipper_configuration => FlipperConfiguration.enabled,
    :hermes_enabled => false, # flags[:hermes_enabled],
    :fabric_enabled => true, # flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BlobCourierExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

