platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!

target 'BlobCourier' do
  use_native_modules!

  target 'BlobCourierTests' do
      inherit! :complete
      # Pods for testing
      pod 'Embassy', '~> 4.1'
      pod 'EnvoyAmbassador', '~> 4.0'
      pod 'MimeParser', '~> 0.2'
  end
end
