require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BlobCourier' do
  platform :ios, '13.0'
  target 'BlobCourierTests' do

     config = use_native_modules!

     use_react_native!(
       :path => config["reactNativePath"],
       # to enable hermes on iOS, change `false` to `true` and then install pods
       :hermes_enabled => false
     )

      # Pods for testing
      pod 'Embassy', '~> 4.1'
      pod 'EnvoyAmbassador', '~> 4.0'
      pod 'MimeParser', :git => "https://github.com/edeckers/MimeParser.git", :branch => "elydeckers/feature/change-deployment-target"
  end

  post_install do |installer|
    react_native_post_install(installer)

    # But... doing so caused another issue in Flipper:
    #   "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make a patch to RCT-Folly - remove the `__IPHONE_OS_VERSION_MIN_REQUIRED` check.
    # See https://github.com/facebook/flipper/issues/834 for more details.
    time_header = "#{Pod::Config.instance.installation_root.to_s}/Pods/RCT-Folly/folly/portability/Time.h"
    `sed -i -e  $'s/ && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0)//' '#{time_header}'`

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

