name: Build and test
on:
  pull_request:
  push:
    branches:
      - main
      - develop

env: 
  node-version: 12
  android-api-level: 31

jobs:
  build-typescript-linux:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.node-version }}
      - run: TARGET=typescript make clean build
        if: steps.node_modules.outputs.cache-hit != 'true'
  build-typescript-macos:
    runs-on: m1
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.node-version }}
      - run: TARGET=typescript make clean build
        if: steps.node_modules.outputs.cache-hit != 'true'
  build-typescript-lint:
    needs:
      - build-typescript-linux
      - build-typescript-macos
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.node-version }}
      - run: TARGET=typescript make lint
  run-typescript-tests:
    needs: build-typescript-lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.node-version }}
      - run: TARGET=typescript make test
      - uses: actions/upload-artifact@v2
        with:
          name: ts-test-results
          path: output/typescript-test-output.xml
  run-android-lint:
    needs:
      - build-typescript-linux
      - build-typescript-macos
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: TARGET=android make clean lint
  run-android-unit-tests:
    needs: run-android-lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: TARGET=android:unit make clean test
      - uses: actions/upload-artifact@v2
        with:
          name: android-unit-test-results
          path: android/build/test-results/**/*.xml
  run-android-instrumented-tests:
    needs: run-android-lint
    continue-on-error: true
    runs-on: m1
    steps: 
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: reactivecircus/android-emulator-runner@v2.20.0
        env:
          ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
          ORG_GRADLE_PROJECT_ADB_COMMAND_TIMEOUT_MILLISECONDS: ${{ secrets.ORG_GRADLE_PROJECT_ADB_COMMAND_TIMEOUT_MILLISECONDS }}
          ORG_GRADLE_PROJECT_PROMISE_TIMEOUT_MILLISECONDS: ${{ secrets.ORG_GRADLE_PROJECT_PROMISE_TIMEOUT_MILLISECONDS }}
          TARGET: android:instrumented
        with:
          api-level: ${{ env.android-api-level }}
          arch: arm64-v8a
          avd-name: ${{ secrets.ANDROID_AVD_NAME }}
          emulator-options: -no-snapshot -noaudio -no-boot-anim
          force-avd-creation: false
          ram-size: ${{ secrets.ANDROID_AVD_RAM_SIZE }}
          script: |
            adb logcat -c
            adb logcat | tee android_instrumented_logcat.log | grep 'io.deckers.blob_courier' &
            make clean test
          target: google_apis
      - uses: actions/upload-artifact@v2
        with:
          name: android-instrumented-test-results
          path: android/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/*.xml
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: android-instrumented-logcat
          path: android_instrumented_logcat.log
        if: always()
  run-ios-lint:
    needs:
      - build-typescript-linux
      - build-typescript-macos
    runs-on: m1
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: TARGET=ios make lint
  run-ios-tests:
    needs: run-ios-lint
    runs-on: m1
    steps: 
      - uses: actions/checkout@v2
      - run: xcrun simctl boot "iPhone 11" || true
      - uses: actions/cache@v2
        id: node_modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: TARGET=ios make clean test
      - uses: actions/upload-artifact@v2
        with:
          name: ios-test-results
          path: build/reports/**/*.xml